CREATE TABLE Persons (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(500) NOT NULL,
	Age INT NOT NULL
);

CREATE TABLE Genres (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(500) NOT NULL
);

CREATE TABLE Books (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(500) NOT NULL,
	Date INT NOT NULL,
	Author INT REFERENCES Persons(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	genre INT REFERENCES Genres(Id) ON DELETE CASCADE ON UPDATE CASCADE
);